root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp\\main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/main.go"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  dir = "."
  run_after_build = "chmod +x main"

[log]
  level = "debug"