services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      target: dev-stage
    container_name: wish-mate
    hostname: wish-mate
    networks:
      - wishnet
    ports:
      - "${PORT}:5000"
    env_file: ".env"
    command: air -c .air.toml
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - .:/app
      - /app/tmp

  postgres:
    extends:
      service: postgres
      file: docker-compose.base.yml
volumes:
  postgres-data:

networks:
  wishnet:
    driver: bridge