services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    hostname: db
    networks:
      - wishnet
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/postgres/postgres-data

  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379